definitions:
  schema.Book:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      edition:
        type: string
      id:
        type: string
      name:
        type: string
      publisherYear:
        type: string
      updatedAt:
        type: string
    type: object
  types.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  types.UpdateBookRequest:
    properties:
      authors:
        items:
          type: string
        type: array
      edition:
        type: string
      name:
        type: string
      publisher_year:
        type: string
    type: object
info:
  contact: {}
paths:
  /books:
    delete:
      consumes:
      - application/json
      description: Deletes a book from the database based on the provided ID.
      parameters:
      - description: Book ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Delete a book
      tags:
      - books
    get:
      consumes:
      - application/json
      description: Get books based on provided filters (id, name, edition, publisher_year)
        or return all books if no filter is provided
      parameters:
      - description: Book ID
        in: query
        name: id
        type: string
      - description: Book Name
        in: query
        name: name
        type: string
      - description: Book Edition
        in: query
        name: edition
        type: string
      - description: Publisher Year
        in: query
        name: publisher_year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get books by various filters
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Update book details based on provided ID. Supports updating name,
        edition, publisher year, and authors.
      parameters:
      - description: Book ID
        in: query
        name: id
        required: true
        type: string
      - description: Update Book Request
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/types.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Update a book
      tags:
      - books
swagger: "2.0"
